# Yacine Mahdid April 8 2020
This script is addressing one part of this issue: https://github.com/BIAPT/awareness-perturbation-complexity-index/issues/10

## Warning
This notebook is trying to address the issue however, it was more complicated than we thought and Danielle ended up giving me the maping via slack. It is sitting in the data folder of ex_10 folder under the name bp_to_egi_danielle.csv. This notebook was left here to keep track of what was tried during this experiment.


## The inital plan was the following:

The purpose of this script is to build on Danielle Nadin work and construct a csv file which will be a mapping between BP headset channel location to EGI headset channel location. Right now this isn't possible since we have in the file `BPtoEGI.xlsx` three columns: [EGI location, BP location, order_from_bp_to_egi] . There isn't a direct one to one mapping between the rows.

We will simplify the file and name it `simplified_bp_to_egi.csv` and use the ordering column to create the file `bp_to_egi_mapping.csv` 

## However
After looking at the WSAS02 tab in the excell book I realized that there was too few channels to map completely from one headset to another (as seen in the rest of the pipeline script when I tried to load the data and map them, I was missing channel). Therefore I simply took the first page and used the first mapping column and deleted everything else. I then saved that as a CSV.

In [37]:
import pandas as pd

source_file_path = "/home/yacine/Documents/BIAPT/awareness-perturbation-complexity-index/.doc/wsas02_information/simplified_bp_to_egi.csv"
target_file_path = "/home/yacine/Documents/BIAPT/awareness-perturbation-complexity-index/.doc/wsas02_information/bp_to_egi_mapping.csv"
df = pd.read_csv(source_file_path)  
df

   egi_location bp_location  egi_to_bp_mapping
0          'E2'       'Fp1'                  7
1          'E3'       'AF7'                 10
2          'E4'       'AF3'                  8
3         'Fp2'        'F3'                  9
4          'Fz'        'F5'                 11
5         'E15'        'F7'                 13
6         'Fp1'       'FT7'                 16
7         'E23'       'FC5'                 14
8          'F3'       'FC3'                 12
9         'E26'        'C3'                 15
10        'E27'        'C5'                 17
11        'E28'        'T7'                 19
12         'F7'       'CP5'                 20
13        'E34'       'CP3'                 18
14         'C3'       'CP1'                 22
15        'E39'        'P1'                 26
16        'E40'        'P3'                 25
17        'E42'        'P5'                 21
18         'T7'        'P7'                 24
19        'E46'       'PO7'                 27
20        'E51'       'PO3'                 28
21        'E53'        'O1'                 29
22        'E55'        'Oz'                 31
23         'P7'       'POz'                 30
24        'E59'       'CPz'                 23
25        'E60'       'Fpz'                  6
26        'E65'       'Fp2'                  4
27        'E66'       'AF8'                  1
28         'O1'       'AF4'                  2
29        'E72'        'Fz'                  5
30         'Oz'        'F2'                  3
31        'E84'        'F4'                 51
32        'E85'        'F6'                 50
33        'E90'        'F8'                 49
34        'E91'       'FT8'                 46
35        'E93'       'FC6'                 47
36         'P8'       'FC4'                 48
37        'E97'       'FC2'                 45
38       'E101'        'Cz'                 52
39       'E102'        'C2'                 42
40         'C4'        'C4'                 41
41       'E105'        'C6'                 44
42         'T8'        'T8'                 43
43       'E109'       'TP8'                 39
44       'E112'       'CP6'                 40
45       'E115'       'CP4'                 36
46       'E116'        'P2'                 33
47       'E117'        'P4'                 35
48         'F8'        'P6'                 38
49       'E123'        'P8'                 37
50         'F4'       'PO8'                 34
51         'Cz'       'PO4'                 32

In [39]:
order = [x-1 for x in list(df.egi_to_bp_mapping)] # get the ordering and reindex to start a 0

# we will iterate through the bp location and find the each index in the order list
# this will allow us to fetch the right label in the bp_location table
reorder_bp_location = []
for i in range(len(order)):
    index = order.index(i)
    reorder_bp_location.append(df.bp_location[index])

fix_df = df.copy()
fix_df['bp_location'] = reorder_bp_location
fix_df = fix_df.drop(columns=['egi_to_bp_mapping'])
fix_df.to_csv(target_file_path, index=False)  
fix_df

   egi_location bp_location
0          'E2'       'AF8'
1          'E3'       'AF4'
2          'E4'        'F2'
3         'Fp2'       'Fp2'
4          'Fz'        'Fz'
5         'E15'       'Fpz'
6         'Fp1'       'Fp1'
7         'E23'       'AF3'
8          'F3'        'F3'
9         'E26'       'AF7'
10        'E27'        'F5'
11        'E28'       'FC3'
12         'F7'        'F7'
13        'E34'       'FC5'
14         'C3'        'C3'
15        'E39'       'FT7'
16        'E40'        'C5'
17        'E42'       'CP3'
18         'T7'        'T7'
19        'E46'       'CP5'
20        'E51'        'P5'
21        'E53'       'CP1'
22        'E55'       'CPz'
23         'P7'        'P7'
24        'E59'        'P3'
25        'E60'        'P1'
26        'E65'       'PO7'
27        'E66'       'PO3'
28         'O1'        'O1'
29        'E72'       'POz'
30         'Oz'        'Oz'
31        'E84'       'PO4'
32        'E85'        'P2'
33        'E90'       'PO8'
34        'E91'        'P4'
35        'E93'       'CP4'
36         'P8'        'P8'
37        'E97'        'P6'
38       'E101'       'TP8'
39       'E102'       'CP6'
40         'C4'        'C4'
41       'E105'        'C2'
42         'T8'        'T8'
43       'E109'        'C6'
44       'E112'       'FC2'
45       'E115'       'FT8'
46       'E116'       'FC6'
47       'E117'       'FC4'
48         'F8'        'F8'
49       'E123'        'F6'
50         'F4'        'F4'
51         'Cz'        'Cz'